# Generated by Django 5.2 on 2025-06-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmu_converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
