# Generated by Django 5.2 on 2025-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmu_converter', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='founderAuthority',
            field=models.CharField(default='96301014', max_length=8),
            preserve_default=False,
        ),
    ]
