# Generated by Django 5.2 on 2025-09-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmu_converter', '0006_alter_actssettingtheprice_numberact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actssettingtheprice',
            name='dateAct',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Нормативный правовой акт: дата'),
        ),
        migrations.AlterField(
            model_name='actssettingtheprice',
            name='numberAct',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Нормативный правовой акт: номер'),
        ),
        migrations.AlterField(
            model_name='indicatorsqualityservice',
            name='OKEI',
            field=models.PositiveIntegerField(default=0, verbose_name='Показатель качества муниципальной услуги: единица измерения: код по ОКЕИ'),
        ),
        migrations.AlterField(
            model_name='indicatorsqualityservice',
            name='absoluteValuesDeviations',
            field=models.PositiveIntegerField(default=0, verbose_name='Допустимые (возможные) отклонения от установленных показателей качества муниципальной услуги: в абсолютных величинах'),
        ),
        migrations.AlterField(
            model_name='indicatorsqualityservice',
            name='percentageDeviations',
            field=models.PositiveIntegerField(default=0, verbose_name='Допустимые (возможные) отклонения от установленных показателей качества муниципальной услуги: в процентах'),
        ),
        migrations.AlterField(
            model_name='indicatorsqualityservice',
            name='valuesQualityIndicatorFirstYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Значение показателя качества муниципальной услуги: (1-й год планового периода)'),
        ),
        migrations.AlterField(
            model_name='indicatorsqualityservice',
            name='valuesQualityIndicatorNextYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Значение показателя качества муниципальной услуги: (очередной финансовый год)'),
        ),
        migrations.AlterField(
            model_name='indicatorsqualityservice',
            name='valuesQualityIndicatorSecondYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Значение показателя качества муниципальной услуги: (2-й год планового периода)'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='OKEI',
            field=models.PositiveIntegerField(default=0, verbose_name='Показатель объема муниципальной услуги:\tединица измерения: единица измерения по ОКЕИ'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='absoluteValuesDeviations',
            field=models.PositiveIntegerField(default=0, verbose_name='Допустимые (возможные) отклонения от установленных показателей объема муниципальной услуги: в абсолютных величинах'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='amountFeeFirstYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер платы (цена, тариф): (1-й год планового периода)'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='amountFeeNextYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер платы (цена, тариф): (очередной финансовый год)'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='amountFeeSecondYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер платы (цена, тариф): (2-й год планового периода)'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='percentageDeviations',
            field=models.PositiveIntegerField(default=0, verbose_name='Допустимые (возможные) отклонения от установленных показателей объема муниципальной услуги: в процентах'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='valuesVolumeIndicatorFirstYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Значение показателя объема государственной услуги: (1-й год планового периода)'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='valuesVolumeIndicatorNextYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Значение показателя объема государственной услуги: (очередной финансовый год)'),
        ),
        migrations.AlterField(
            model_name='indicatorsvolumeservice',
            name='valuesVolumeIndicatorSecondYear',
            field=models.PositiveIntegerField(default=0, verbose_name='Значение показателя объема государственной услуги: (2-й год планового периода)'),
        ),
    ]
