# Generated by Django 5.2 on 2025-09-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmu_converter', '0007_alter_actssettingtheprice_dateact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actssettingtheprice',
            name='regulatingAct',
        ),
        migrations.RemoveField(
            model_name='indicatorsqualityservice',
            name='regulatingAct',
        ),
        migrations.RemoveField(
            model_name='indicatorsvolumeservice',
            name='regulatingAct',
        ),
        migrations.RemoveField(
            model_name='informingpotentialconsumersoftheservice',
            name='regulatingAct',
        ),
    ]
