# Generated by Django 5.2 on 2025-09-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmu_converter', '0008_remove_actssettingtheprice_regulatingact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatingAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год формирования отчета')),
                ('typeAct', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Нормативный правовой акт: вид')),
                ('receivingBody', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Нормативный правовой акт: принявший орган')),
                ('dateAct', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Нормативный правовой акт: дата')),
                ('numberAct', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Нормативный правовой акт: номер')),
                ('nameAct', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Нормативный правовой акт: наименование')),
                ('section', models.PositiveIntegerField(verbose_name='Номер раздела')),
                ('serviceName', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Наименование муниципальной услуги')),
                ('consumerCategory', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Категории потребителей муниципальной услуги')),
                ('codeBasicList', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Код по общероссийскому базовому перечню или федеральному перечню')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulating_act', to='gmu_converter.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Нормативные правовые акты, регулирующие порядок оказания государственной услуги',
                'verbose_name_plural': 'Нормативные правовые акты, регулирующие порядок оказания государственной услуги',
            },
        ),
    ]
