export const fhdSchemaList2 = {
    planPaymentTRU: [
        {field: "lineNum", label: "Номер строки"},
        {field: "kbk", label: "Код бюджетной классификации"},
        {field: "name", label: "Наименование показателя"},
        {field: "lineCode", label: "Код строки"},
        {field: "yearStart", label: "Год начала закупки"},
        {
            field: "uniqueCode",
            label: "Уникальный код объекта капитального, строительства, объекта недвижимого имущества"
        },
        {field: "manually", label: "false"},
        {field: "financialYearSum", label: "Сумма на текущий финансовый год"},
        {field: "planFirstYearSum", label: "Сумма на первый год планового периода"},
        {field: "planLastYearSum", label: "Сумма на второй год планового периода"},
        {field: "AutPlanYearSumm", label: "Сумма за пределами планового периода"},
        {field: "actions", label: ""}
    ],
    defaultPaymentTRU: [
        {
            "lineNum": "1.",
            "kbk": "",
            "name": "Выплаты на закупку товаров, работ, услуг, всего в том числе:",
            "lineCode": "26000",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.1.",
            "kbk": "",
            "name": "по контрактам (договорам), заключенным до начала текущего финансового года без применения норм Федерального закона от 5 апреля 2013 г. № 44-ФЗ «О контрактной системе в сфере закупок товаров, работ, услуг для обеспечения государственных и муниципальных нужд» (Собрание законодательства Российской Федерации, 2013, № 14, ст. 1652; 2018, № 32, ст. 5104) (далее — Федеральный закон № 44-ФЗ) и Федерального закона от 18 июля 2011 г. № 223-ФЗ «О закупках товаров, работ, услуг отдельными видами юридических лиц» (Собрание законодательства Российской Федерации, 2011, № 30, ст. 4571; 2018, № 32, ст. 5135) (далее — Федеральный закон № 223-ФЗ)",
            "lineCode": "26100",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.2.",
            "kbk": "",
            "name": "по контрактам (договорам), планируемым к заключению в соответствующем финансовом году без применения норм Федерального закона № 44-ФЗ и Федерального закона № 223-ФЗ",
            "lineCode": "26200",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.3.",
            "kbk": "",
            "name": "по контрактам (договорам), заключенным до начала текущего финансового года с учетом требований Федерального закона № 44-ФЗ и Федерального закона № 223-ФЗ в том числе:",
            "lineCode": "26300",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.3.1.",
            "kbk": "X",
            "name": "в соответствии с Федеральным законом № 44-ФЗ из них:",
            "lineCode": "26310",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.3.2.",
            "kbk": "X",
            "name": "в соответствии с Федеральным законом № 223-ФЗ",
            "lineCode": "26320",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.",
            "kbk": "",
            "name": "по контрактам (договорам), планируемым к заключению в соответствующем финансовом году с учетом требований Федерального закона № 44-ФЗ и Федерального закона № 223-ФЗ в том числе:",
            "lineCode": "26400",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.1.",
            "kbk": "",
            "name": "за счет субсидий, предоставляемых на финансовое обеспечение выполнения государственного (муниципального) задания в том числе:",
            "lineCode": "26410",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.1.1.",
            "kbk": "",
            "name": "в соответствии с Федеральным законом № 44-ФЗ",
            "lineCode": "26411",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.1.2.",
            "kbk": "",
            "name": "в соответствии с Федеральным законом № 223-ФЗ",
            "lineCode": "26412",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.2.",
            "kbk": "",
            "name": "за счет субсидий, предоставляемых в соответствии с абзацем вторым пункта 1 статьи 78.1 Бюджетного кодекса Российской Федерации в том числе:",
            "lineCode": "26420",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.2.1",
            "kbk": "",
            "name": "в соответствии с Федеральным законом № 44-ФЗ из них:",
            "lineCode": "26421",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.2.2.",
            "kbk": "",
            "name": "в соответствии с Федеральным законом № 223-ФЗ",
            "lineCode": "26422",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.3.",
            "kbk": "",
            "name": "за счет субсидий, предоставляемых на осуществление капитальных вложений из них:",
            "lineCode": "26430",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.4.",
            "kbk": "",
            "name": "за счет средств обязательного медицинского страхования в том числе:",
            "lineCode": "26440",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.4.1.",
            "kbk": "",
            "name": "в соответствии с Федеральным законом № 44-ФЗ",
            "lineCode": "26441",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.4.2.",
            "kbk": "",
            "name": "в соответствии с Федеральным законом № 223-ФЗ",
            "lineCode": "26442",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.5.",
            "kbk": "",
            "name": "за счет прочих источников финансового обеспечения в том числе:",
            "lineCode": "26450",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.5.1.",
            "kbk": "",
            "name": "в соответствии с Федеральным законом № 44-ФЗ из них:",
            "lineCode": "26451",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "1.4.5.2.",
            "kbk": "",
            "name": "в соответствии с Федеральным законом № 223-ФЗ",
            "lineCode": "26452",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "2.",
            "kbk": "",
            "name": "Итого по контрактам, планируемым к заключению в соответствующем финансовом году в соответствии с Федеральным законом № 44-ФЗ, по соответствующему году закупки в том числе по году начала закупки:",
            "lineCode": "26500",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        },
        {
            "lineNum": "3.",
            "kbk": "",
            "name": "Итого по договорам, планируемым к заключению в соответствующем финансовом году в соответствии с Федеральным законом № 223-ФЗ, по соответствующему году закупки в том числе по году начала закупки:",
            "lineCode": "26600",
            "yearStart": "X",
            "uniqueCode": "",
            "manually": "false",
            "financialYearSum": "",
            "planFirstYearSum": "",
            "planLastYearSum": "",
            "AutPlanYearSumm": ""
        }
    ]
}