# Generated by Django 5.2 on 2025-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('FIO', models.TextField()),
                ('INN', models.CharField(max_length=10)),
                ('KPP', models.CharField(max_length=9)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('BANK', models.TextField()),
                ('UBP', models.CharField(max_length=8)),
            ],
        ),
    ]
