# Generated by Django 5.2 on 2025-05-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPaymentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год формирования отчета')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование показателя')),
                ('lineCode', models.CharField(max_length=50, verbose_name='Код строки')),
                ('kbk', models.CharField(max_length=100, verbose_name='Код по бюджетной классификации')),
                ('analyticCode', models.CharField(max_length=100, verbose_name='Аналитический код')),
                ('manually', models.BooleanField(default=False, verbose_name='Признак добавленной строки')),
                ('financialYearSum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма на текущий финансовый год')),
                ('planFirstYearSum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма на первый год планового периода')),
                ('planLastYearSum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма на второй год планового периода')),
                ('AutPlanYearSumm', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма за пределами планового периода')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_payment_indices', to='MBDOU_INF.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Показатель плана платежей',
                'verbose_name_plural': 'Показатели плана платежей',
            },
        ),
        migrations.CreateModel(
            name='PlanPaymentTRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год формирования отчета')),
                ('line_num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки')),
                ('kbk', models.CharField(max_length=100, verbose_name='Код бюджетной классификации')),
                ('name', models.TextField(verbose_name='Наименование показателя')),
                ('line_code', models.CharField(max_length=50, verbose_name='Код строки')),
                ('year_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год начала закупки')),
                ('unique_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникальный код объекта')),
                ('manually', models.BooleanField(default=False, verbose_name='Признак добавленной строки')),
                ('financial_year_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма на текущий финансовый год')),
                ('plan_first_year_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма на первый год планового периода')),
                ('plan_last_year_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма на второй год планового периода')),
                ('aut_plan_year_summ', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма за пределами планового периода')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_payment_tru', to='MBDOU_INF.organization')),
            ],
            options={
                'verbose_name': 'Планируемый платёж',
                'verbose_name_plural': 'Планируемые платежи',
            },
        ),
    ]
