# Generated by Django 5.2 on 2025-05-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0002_planpaymentindex_planpaymenttru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planpaymenttru',
            old_name='aut_plan_year_summ',
            new_name='AutPlanYearSumm',
        ),
        migrations.RenameField(
            model_name='planpaymenttru',
            old_name='financial_year_sum',
            new_name='financialYearSum',
        ),
        migrations.RenameField(
            model_name='planpaymenttru',
            old_name='line_code',
            new_name='lineCode',
        ),
        migrations.RenameField(
            model_name='planpaymenttru',
            old_name='line_num',
            new_name='lineNum',
        ),
        migrations.RenameField(
            model_name='planpaymenttru',
            old_name='plan_first_year_sum',
            new_name='planFirstYearSum',
        ),
        migrations.RenameField(
            model_name='planpaymenttru',
            old_name='plan_last_year_sum',
            new_name='planLastYearSum',
        ),
        migrations.RenameField(
            model_name='planpaymenttru',
            old_name='unique_code',
            new_name='uniqueCode',
        ),
        migrations.RenameField(
            model_name='planpaymenttru',
            old_name='year_start',
            new_name='yearStart',
        ),
    ]
