# Generated by Django 5.2 on 2025-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0003_rename_aut_plan_year_summ_planpaymenttru_autplanyearsumm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpaymentindex',
            name='analyticCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аналитический код'),
        ),
        migrations.AlterField(
            model_name='planpaymentindex',
            name='kbk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код по бюджетной классификации'),
        ),
        migrations.AlterField(
            model_name='planpaymentindex',
            name='lineCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код строки'),
        ),
        migrations.AlterField(
            model_name='planpaymentindex',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование показателя'),
        ),
        migrations.AlterField(
            model_name='planpaymenttru',
            name='kbk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код бюджетной классификации'),
        ),
        migrations.AlterField(
            model_name='planpaymenttru',
            name='lineCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код строки'),
        ),
        migrations.AlterField(
            model_name='planpaymenttru',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование показателя'),
        ),
    ]
