# Generated by Django 5.2 on 2025-05-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0004_alter_planpaymentindex_analyticcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpaymentindex',
            name='analyticCode',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Аналитический код'),
        ),
        migrations.AlterField(
            model_name='planpaymentindex',
            name='kbk',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Код по бюджетной классификации'),
        ),
        migrations.AlterField(
            model_name='planpaymentindex',
            name='lineCode',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Код строки'),
        ),
        migrations.AlterField(
            model_name='planpaymentindex',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Наименование показателя'),
        ),
        migrations.AlterField(
            model_name='planpaymentindex',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_payment_index', to='MBDOU_INF.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='planpaymenttru',
            name='kbk',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Код бюджетной классификации'),
        ),
        migrations.AlterField(
            model_name='planpaymenttru',
            name='lineCode',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Код строки'),
        ),
        migrations.AlterField(
            model_name='planpaymenttru',
            name='uniqueCode',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Уникальный код объекта'),
        ),
    ]
