# Generated by Django 5.2 on 2025-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0005_alter_planpaymentindex_analyticcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpaymentindex',
            name='analyticCode',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Аналитический код'),
        ),
    ]
