# Generated by Django 5.2 on 2025-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0005_actssettingtheprice_indicatorsqualityservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actssettingtheprice',
            name='numberAct',
            field=models.PositiveIntegerField(blank=True, default='', null=True, verbose_name='Нормативный правовой акт: номер'),
        ),
    ]
