# Generated by Django 5.2 on 2025-05-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0007_alter_planpaymentindex_analyticcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpaymentindex',
            name='analyticCode',
            field=models.TextField(blank=True, null=True, verbose_name='Аналитический код'),
        ),
    ]
