# Generated by Django 5.2 on 2025-05-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0008_alter_planpaymentindex_analyticcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpaymentindex',
            name='analyticCode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Аналитический код'),
        ),
    ]
