# Generated by Django 5.2 on 2025-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0009_alter_planpaymentindex_analyticcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpaymenttru',
            name='lineNum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер строки'),
        ),
        migrations.AlterField(
            model_name='planpaymenttru',
            name='yearStart',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Год начала закупки'),
        ),
    ]
