# Generated by Django 5.2 on 2025-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0010_alter_planpaymenttru_linenum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpaymentindex',
            name='afterLineCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код строки, после которой добавлена'),
        ),
        migrations.AddField(
            model_name='planpaymenttru',
            name='afterLineCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код строки, после которой добавлена'),
        ),
    ]
