# Generated by Django 5.2 on 2025-05-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBDOU_INF', '0011_planpaymentindex_afterlinecode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planpaymentindex',
            options={'ordering': ['lineCode'], 'verbose_name': 'Показатель плана платежей', 'verbose_name_plural': 'Показатели плана платежей'},
        ),
        migrations.AlterModelOptions(
            name='planpaymenttru',
            options={'ordering': ['lineCode'], 'verbose_name': 'Планируемый платёж', 'verbose_name_plural': 'Планируемые платежи'},
        ),
    ]
